# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('ceptel', models.IntegerField(max_length=11, verbose_name='Cep Tel.')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('tckimlik', models.IntegerField(max_length=11, verbose_name='Tc Kimlik')),
                ('okulno', models.IntegerField(max_length=5, verbose_name='Okul Numarası')),
            ],
        ),
    ]
