# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='ceptel',
            field=models.IntegerField(verbose_name='Cep Tel.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='okulno',
            field=models.IntegerField(verbose_name='Okul Numarası'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tckimlik',
            field=models.IntegerField(verbose_name='Tc Kimlik'),
        ),
    ]
