# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_guardian_whoseguardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1, upload_to='images/student'),
            preserve_default=False,
        ),
    ]
