# Generated by Django 2.2.2 on 2019-07-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190719_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
            ],
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
